### PR TITLE
Switch from `babel-eslint` to `@babel/eslint-parser`

### LINKED ISSUE #11: Migrate to @babel/eslint-parser
Seems like eslint-template-visitor is the only dependency (when using eslint-plugin-unicorn) that is still holding babel-eslint@10.1.0 in the dependency tree.

Will it be possible to migrate over to the [@babel/eslint-parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser) in the near future?
https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint

### PR DESCRIPTION
**Pull request by futpib**
I think this will have to wait for [babel](https://github.com/babel/babel) version 8 release

Fixes #11

### CODE REVIEW

**Comment by brettz9** [comment]
`babel-eslint` is now deprecated in favor of `@babel/eslint-parser`. Was it due to it having been experimental until recently that you are holding back or some other reason?

**Comment by fregante** [comment]
> I think this will have to wait for [babel](https://github.com/babel/babel) version 8 release

Why babel 8? `@babel/` packages have been introduced in babel 7 I think

**Comment by futpib** [comment]
Thanks for reminders! `@babel/eslint-parser` was experimental and promised to be released with Babel v8 in the [README](https://www.npmjs.com/package/@babel/eslint-parser/v/7.11.0) at the time I first considered this upgrade.

**Comment by papandreou** [comment]
I use this module via `eslint-plugin-unicorn`, and this broke my build because it now requires `@babel/core` as a peer dep:

```
$ eslint .

Oops! Something went wrong! :(

ESLint: 7.20.0

Error: Failed to load plugin 'unicorn' declared in '.eslintrc » ./.': Cannot find module '@babel/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (/Users/andreaslind/work/eslint-config/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/andreaslind/work/eslint-config/node_modules/@babel/eslint-parser/lib/index.js:11:13)
    at Module._compile (/Users/andreaslind/work/eslint-config/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

A bit of a curveball to introduce such a requirement in a minor version 😓

**Comment by futpib** [comment]
Sorry 😞 I changed it to explicit dependency in 2.3.1.

**Comment by papandreou** [comment]
@futpib, thanks for that! Sorry if I sounded whiny 🤗

**Pull request merged**
